import {
  ArrowRightIcon,
  BadgeCheckIcon,
  BookOpenIcon,
  CameraIcon,
  Code2Icon,
  FileDownIcon,
  GaugeIcon,
  RefreshCwIcon,
  ScanSearchIcon,
} from "lucide-react";
import { productScreenshots } from "@/content/screenshots";
import { getAllDocPages } from "@/lib/docs";
import { assetPath, siteConfig, withBasePath } from "@/lib/site";
import { SiteShell } from "@/components/site-shell";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

const featureCards = [
  {
    title: "Evidence-first scanning",
    copy: "Sitemap and single-page scans run in Chromium, capture focused screenshots, and keep selectors and HTML context for review.",
    icon: ScanSearchIcon,
    className: "md:col-span-3 xl:col-span-5",
  },
  {
    title: "Same-scan recovery",
    copy: "Retry failed pages in place for partial scans. No second scan ID, no duplicate report, no full rerun tax.",
    icon: RefreshCwIcon,
    className: "md:col-span-3 xl:col-span-4",
  },
  {
    title: "Large-report performance",
    copy: "Issue cards, occurrence details, and exports are bounded, paginated, cached, or streamed where it matters.",
    icon: GaugeIcon,
    className: "md:col-span-6 xl:col-span-3",
  },
  {
    title: "Human, data, and AI reports",
    copy: "PDF for audit review, CSV for data workflows, and compact LLM text for assisted remediation planning.",
    icon: FileDownIcon,
    className: "md:col-span-3 xl:col-span-4",
  },
  {
    title: "Operator-ready deployment",
    copy: "Docker, Fly.io, GHCR images, release bundles, and changelog-generated release notes are documented together.",
    icon: BadgeCheckIcon,
    className: "md:col-span-3 xl:col-span-4",
  },
  {
    title: "Developer surface",
    copy: "Architecture notes, contribution flow, API docs, and the docs screenshot pipeline live in the public site.",
    icon: Code2Icon,
    className: "md:col-span-6 xl:col-span-4",
  },
];

export default function HomePage() {
  const docs = getAllDocPages().filter((page) => page.category !== "Reference");
  const heroShot =
    productScreenshots.find((shot) => shot.id === "issues") ?? productScreenshots[0];

  return (
    <SiteShell>
    <main className="mx-auto w-full max-w-7xl px-4 py-8 md:px-8 md:py-12">
      <section className="grid gap-4 xl:grid-cols-[1.05fr_0.95fr]">
        <Card className="overflow-hidden border-black/10 bg-[#FFED00] py-0 text-black">
          <CardContent className="relative min-h-[560px] p-8 md:p-12">
            <h1 className="max-w-3xl font-heading text-[clamp(4rem,12vw,9rem)] leading-[0.82] tracking-[-0.07em]">
              Audit with proof.
            </h1>
            <p className="mt-6 max-w-2xl text-lg leading-8 text-black/72">
              LIME scans real pages, captures screenshots, groups issues, retries
              partial failures in place, and exports reports that developers,
              auditors, and AI tools can use.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Button variant="default" size="lg" asChild>
                <a href={withBasePath("/docs/user/first-scan/")}>
                  Start with user docs <ArrowRightIcon className="size-4" />
                </a>
              </Button>
              <Button variant="outline" size="lg" className="border-black/20 bg-white/70" asChild>
                <a href={siteConfig.releasesUrl}>Download latest release</a>
              </Button>
            </div>
          </CardContent>
        </Card>

        <div className="grid gap-4">
          <Card className="overflow-hidden py-0">
            <div className="border-b bg-muted p-2">
              <img
                src={assetPath(heroShot.src)}
                alt={heroShot.alt}
                className="aspect-[16/11] w-full rounded-lg border bg-white object-cover"
              />
            </div>
            <CardHeader>
              <CardTitle>Real docs-demo screenshots</CardTitle>
              <CardDescription>
                Generated by isolated public demo scans, including intentionally
                inaccessible pages for richer issue examples.
              </CardDescription>
            </CardHeader>
          </Card>
          <div className="grid gap-4 md:grid-cols-3">
            <Card className="py-4">
              <CardContent>
                <div className="font-heading text-xl font-bold">User workflow</div>
                <p className="mt-1 text-xs text-muted-foreground">Create scans, inspect results, retry partials.</p>
              </CardContent>
            </Card>
            <Card className="py-4">
              <CardContent>
                <div className="font-heading text-xl font-bold">Evidence</div>
                <p className="mt-1 text-xs text-muted-foreground">Screenshots, selectors, HTML, and ACT links.</p>
              </CardContent>
            </Card>
            <Card className="py-4">
              <CardContent>
                <div className="font-heading text-xl font-bold">Exports</div>
                <p className="mt-1 text-xs text-muted-foreground">PDF, CSV, and LLM-ready text reports.</p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      <section className="mt-4 bento-grid">
        {featureCards.map((feature) => {
          const Icon = feature.icon;
          return (
            <Card key={feature.title} className={feature.className}>
              <CardHeader>
                <div className="mb-4 flex size-10 items-center justify-center rounded-xl bg-[#FFED00] text-black">
                  <Icon className="size-5" />
                </div>
                <CardTitle>{feature.title}</CardTitle>
                <CardDescription>{feature.copy}</CardDescription>
              </CardHeader>
            </Card>
          );
        })}
      </section>

      <section className="mt-4 grid gap-4 xl:grid-cols-[0.9fr_1.1fr]">
        <Card className="bg-black text-[#fffbe6]">
          <CardHeader>
            <CardTitle className="text-3xl">Run it locally.</CardTitle>
            <CardDescription className="text-[#fffbe6]/70">
              The release path stays simple: Docker for the product, static
              export for docs, and a dedicated command for screenshot refresh.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <pre className="overflow-x-auto rounded-2xl border border-white/10 bg-white/5 p-4 text-sm leading-7">
{`git clone https://github.com/sumanbasuli/lime.git
cd lime
cp .env.example .env
make start-all

make docs-run    # build and serve static docs
make docs-dev    # docs hot reload server
make docs        # isolated screenshot refresh`}
            </pre>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle className="text-3xl">Documentation sets</CardTitle>
            <CardDescription>
              User docs explain how to operate the tool. Developer docs explain
              how to contribute, extend, deploy, and integrate with it.
            </CardDescription>
          </CardHeader>
          <CardContent className="grid gap-3 md:grid-cols-3">
            <Button variant="outline" className="h-auto justify-start p-4" asChild>
              <a href={withBasePath("/docs/user/first-scan/")}>
                <BookOpenIcon className="size-5" />
                User docs
              </a>
            </Button>
            <Button variant="outline" className="h-auto justify-start p-4" asChild>
              <a href={withBasePath("/docs/developer/contributing/")}>
                <Code2Icon className="size-5" />
                Developer docs
              </a>
            </Button>
            <Button variant="outline" className="h-auto justify-start p-4" asChild>
              <a href={withBasePath("/screenshots/")}>
                <CameraIcon className="size-5" />
                Screenshots
              </a>
            </Button>
          </CardContent>
        </Card>
      </section>

      <section className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {docs.slice(0, 6).map((doc) => (
          <Card key={doc.href}>
            <CardHeader>
              <span className="mb-3 w-fit rounded-full border bg-muted px-2.5 py-1 text-xs font-medium text-muted-foreground">
                {doc.category}
              </span>
              <CardTitle>{doc.title}</CardTitle>
              <CardDescription>{doc.excerpt}</CardDescription>
            </CardHeader>
            <CardContent>
              <Button variant="ghost" className="px-0" asChild>
                <a href={withBasePath(doc.href)}>
                  Read doc <ArrowRightIcon className="size-4" />
                </a>
              </Button>
            </CardContent>
          </Card>
        ))}
      </section>
    </main>
    </SiteShell>
  );
}
